import React, { useState, useEffect } from 'react';
import Sidebar from '../components/common/Sidebar';
import Navbar from '../components/common/Navbar';
import LoadingSpinner from '../components/common/LoadingSpinner';
import ErrorAlert from '../components/common/ErrorAlert';
import { apiClient } from '../api/client';
import {
  ShieldAlert, AlertTriangle, CheckCircle2, Lock, Sparkles, Loader2, Globe, ArrowRight,
  ShieldCheck, FileText, Activity, Terminal, Shield, RefreshCw, Zap
} from 'lucide-react';

export const FraudDetectionPage = () => {
  const [activeTab, setActiveTab] = useState('threat_feed'); // 'threat_feed' | 'simulator' | 'sar_generator'
  const [fraudAlerts, setFraudAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [analyzingTxId, setAnalyzingTxId] = useState(null);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [frozenAccounts, setFrozenAccounts] = useState([]);

  // Simulator Form State
  const [simTx, setSimTx] = useState({
    accountHolder: 'Apex Industrial Corp',
    accountNumber: 'KSBC-CORP-90004912',
    amount: 980000,
    transactionType: 'International SWIFT Wire',
    location: 'Zurich, Switzerland (Overseas)',
    IPAddress: '185.220.101.5',
    timeOfDay: '03:14 AM EST',
    averageTransactionAmount: 45000
  });
  const [simulating, setSimulating] = useState(false);

  // SAR Filing State
  const [sarReport, setSarReport] = useState(null);
  const [generatingSar, setGeneratingSar] = useState(false);

  const fetchFraudAlerts = async () => {
    try {
      setLoading(true);
      const res = await apiClient.get('/ai/fraud-transactions');
      if (res.data.success) {
        setFraudAlerts(res.data.fraudAlerts);
      }
    } catch (err) {
      setError('Failed to retrieve fraud monitoring feed');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFraudAlerts();
  }, []);

  const handleAnalyzeFraud = async (tx) => {
    setAnalyzingTxId(tx.transactionId);
    setError('');
    try {
      const res = await apiClient.post('/ai/fraud-detection/analyze', tx);
      if (res.data.success) {
        setAnalysisResult(res.data.fraudAnalysis);
      }
    } catch (err) {
      setError(err.response?.data?.error || 'AI Fraud detection analysis failed');
    } finally {
      setAnalyzingTxId(null);
    }
  };

  const handleFreezeAccount = (accNo) => {
    if (!frozenAccounts.includes(accNo)) {
      setFrozenAccounts([...frozenAccounts, accNo]);
    }
  };

  const handleRunSimulator = async (e) => {
    e.preventDefault();
    setSimulating(true);
    setError('');

    try {
      const res = await apiClient.post('/ai/fraud-detection/analyze', simTx);
      if (res.data.success) {
        setAnalysisResult(res.data.fraudAnalysis);
        // Prepend simulated alert to feed
        const newSimAlert = {
          transactionId: `TX-SIM-${Math.floor(1000 + Math.random() * 9000)}`,
          ...simTx,
          fraudScore: res.data.fraudAnalysis.fraudScore || 85,
          riskTag: res.data.fraudAnalysis.riskTag || 'HIGH_RISK_FRAUD',
          status: 'SIMULATED_FLAG'
        };
        setFraudAlerts(prev => [newSimAlert, ...prev]);
        setActiveTab('threat_feed');
      }
    } catch (err) {
      setError(err.response?.data?.error || 'AML Simulator execution failed');
    } finally {
      setSimulating(false);
    }
  };

  const handleGenerateFinCENSar = (tx) => {
    setGeneratingSar(true);
    const targetTx = tx || fraudAlerts[0] || simTx;

    setTimeout(() => {
      setSarReport({
        sarId: `SAR-FINCEN-2026-${Math.floor(100000 + Math.random() * 900000)}`,
        filingInstitution: 'KSBC Digital Banking ERP System',
        subjectName: targetTx.accountHolder || 'Apex Industrial Corp',
        subjectAccount: targetTx.accountNumber || 'KSBC-CORP-90004912',
        totalSuspiciousAmount: Number(targetTx.amount || 850000),
        primaryIndicator: 'Structuring & Overseas High-Velocity Outflow',
        regulatoryFilingDate: new Date().toISOString().split('T')[0],
        narrativeSummary: `Automated FinCEN Suspicious Activity Report (SAR) generated by Gemini 2.5 AML Sentinel. Subject account ${targetTx.accountNumber} engaged in anomalous transaction of $${Number(targetTx.amount).toLocaleString()} from ${targetTx.location || 'Foreign IP'}, exceeding 20x historical average baseline.`,
        recommendedAction: 'Mandatory 30-day Account Freeze & FinCEN Form 111 E-Filing'
      });
      setGeneratingSar(false);
      setActiveTab('sar_generator');
    }, 600);
  };

  return (
    <div className="flex min-h-screen bg-[#FAF7E6] text-[#1E2748]">
      <Sidebar />
      <div className="flex-1 flex flex-col min-w-0 overflow-y-auto">
        <Navbar />

        <main className="p-6 md:p-8 space-y-6 max-w-7xl mx-auto w-full">
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-extrabold text-[#1E2748] font-heading">AI Fraud Detection & AML Security Sentinel</h1>
              <p className="text-xs text-[#1E2748]">Real-Time Gemini 2.5 Anomaly Scoring & Anti-Money Laundering (AML) Threat Matrix</p>
            </div>
            <div className="flex items-center space-x-2 px-3.5 py-1.5 bg-red-500/10 border border-red-500/30 rounded-full text-xs text-red-700 font-bold shadow-sm">
              <ShieldAlert className="w-4 h-4 text-red-600 animate-pulse" />
              <span>AML Anomaly Sentinel Active</span>
            </div>
          </div>

          {/* Navigation Tabs */}
          <div className="flex items-center space-x-3 border-b border-[#1E2748]/15 pb-2">
            <button
              onClick={() => setActiveTab('threat_feed')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition flex items-center space-x-2 border ${
                activeTab === 'threat_feed'
                  ? 'bg-[#1E2748] text-[#FAF7E6] border-[#1E2748] shadow-md font-extrabold'
                  : 'bg-[#F3EEDC] text-[#1E2748] border-[#1E2748]/15 hover:bg-[#EBE4CD]'
              }`}
            >
              <Activity className="w-4 h-4 text-[#C59E5F]" />
              <span>Real-Time AML Threat Feed</span>
            </button>

            <button
              onClick={() => setActiveTab('simulator')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition flex items-center space-x-2 border ${
                activeTab === 'simulator'
                  ? 'bg-[#1E2748] text-[#FAF7E6] border-[#1E2748] shadow-md font-extrabold'
                  : 'bg-[#F3EEDC] text-[#1E2748] border-[#1E2748]/15 hover:bg-[#EBE4CD]'
              }`}
            >
              <Zap className="w-4 h-4 text-[#C59E5F]" />
              <span>Live AML Anomaly Simulator</span>
            </button>

            <button
              onClick={() => setActiveTab('sar_generator')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition flex items-center space-x-2 border ${
                activeTab === 'sar_generator'
                  ? 'bg-[#1E2748] text-[#FAF7E6] border-[#1E2748] shadow-md font-extrabold'
                  : 'bg-[#F3EEDC] text-[#1E2748] border-[#1E2748]/15 hover:bg-[#EBE4CD]'
              }`}
            >
              <FileText className="w-4 h-4 text-[#C59E5F]" />
              <span>FinCEN SAR Report Generator</span>
            </button>
          </div>

          <ErrorAlert message={error} onClose={() => setError('')} />

          {/* TAB 1: REAL-TIME AML THREAT FEED */}
          {activeTab === 'threat_feed' && (
            <div>
              {loading ? (
                <LoadingSpinner text="Connecting to real-time transaction fraud monitoring stream..." />
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
                  {/* Flagged Suspicious Transactions Feed */}
                  <div className="lg:col-span-7 glass-panel p-5 rounded-2xl border border-[#1E2748]/15 space-y-4 bg-[#F3EEDC] shadow-xl">
                    <h3 className="text-sm font-bold text-[#1E2748] flex items-center space-x-2 pb-2 border-b border-[#1E2748]/15">
                      <AlertTriangle className="w-4 h-4 text-red-600" />
                      <span>Flagged Suspicious Transactions ({fraudAlerts.length})</span>
                    </h3>

                    <div className="space-y-3">
                      {fraudAlerts.map((tx) => {
                        const isFrozen = frozenAccounts.includes(tx.accountNumber);
                        return (
                          <div key={tx.transactionId} className="p-4 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15 space-y-3 hover:border-[#1E2748] transition shadow-sm">
                            <div className="flex justify-between items-start">
                              <div>
                                <h4 className="font-bold text-[#1E2748] text-sm">{tx.accountHolder}</h4>
                                <span className="text-[10px] font-mono text-[#1E2748]">
                                  {tx.accountNumber} | {tx.transactionType}
                                </span>
                              </div>

                              <div className="text-right">
                                <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border font-mono uppercase ${
                                  tx.riskTag === 'HIGH_RISK_FRAUD'
                                    ? 'bg-red-500/20 text-red-700 border-red-500/40'
                                    : 'bg-[#1E2748] text-[#FAF7E6] border-[#1E2748]'
                                }`}>
                                  {tx.riskTag.replace(/_/g, ' ')}
                                </span>
                              </div>
                            </div>

                            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs font-mono p-2.5 bg-[#EBE4CD] rounded-lg">
                              <div>
                                <span className="text-[9px] text-[#1E2748] font-sans block font-bold">AMOUNT</span>
                                <span className="font-extrabold text-red-600">${Number(tx.amount).toLocaleString()}</span>
                              </div>
                              <div>
                                <span className="text-[9px] text-[#1E2748] font-sans block font-bold">LOCATION & IP</span>
                                <span className="font-bold text-[#1E2748] text-[11px] truncate block">{tx.location}</span>
                              </div>
                              <div>
                                <span className="text-[9px] text-[#1E2748] font-sans block font-bold">FRAUD SCORE</span>
                                <span className="font-extrabold text-[#1E2748]">{tx.fraudScore}/100</span>
                              </div>
                            </div>

                            {/* Action buttons */}
                            <div className="pt-2 border-t border-[#1E2748]/10 flex flex-wrap items-center justify-between gap-2">
                              {isFrozen ? (
                                <span className="px-3 py-1 bg-red-500/20 text-red-700 font-bold rounded-lg text-xs flex items-center space-x-1 border border-red-500/40">
                                  <Lock className="w-3.5 h-3.5" />
                                  <span>Account Frozen & Assets Locked</span>
                                </span>
                              ) : (
                                <button
                                  onClick={() => handleFreezeAccount(tx.accountNumber)}
                                  className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white font-bold rounded-xl text-xs transition shadow-sm"
                                >
                                  Freeze Account Immediately
                                </button>
                              )}

                              <div className="flex items-center space-x-2">
                                <button
                                  onClick={() => handleGenerateFinCENSar(tx)}
                                  className="px-3 py-1.5 bg-[#1E2748] hover:bg-[#141C33] text-[#FAF7E6] text-xs font-bold rounded-xl shadow transition flex items-center space-x-1 border border-[#1E2748]"
                                >
                                  <FileText className="w-3.5 h-3.5 text-[#C59E5F]" />
                                  <span>Generate SAR</span>
                                </button>

                                <button
                                  onClick={() => handleAnalyzeFraud(tx)}
                                  disabled={analyzingTxId === tx.transactionId}
                                  className="px-3.5 py-1.5 bg-[#58b388] hover:bg-[#489973] text-[#1E2748] text-xs font-black rounded-xl shadow transition flex items-center space-x-1.5 disabled:opacity-50"
                                >
                                  {analyzingTxId === tx.transactionId ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5 text-[#1E2748]" />}
                                  <span>Run AI Audit</span>
                                </button>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* AI Fraud Analysis Result Box */}
                  <div className="lg:col-span-5 space-y-4">
                    {analysisResult ? (
                      <div className="glass-panel p-6 rounded-2xl border border-[#1E2748]/15 space-y-4 shadow-2xl bg-[#F3EEDC]">
                        <div className="flex justify-between items-center pb-3 border-b border-[#1E2748]/15">
                          <h3 className="text-base font-bold text-[#1E2748] flex items-center space-x-2">
                            <Sparkles className="w-4 h-4 text-[#C59E5F]" />
                            <span>Gemini AI Fraud Audit</span>
                          </h3>
                          <span className="text-xs font-mono font-black text-red-600">
                            {analysisResult.fraudScore}/100 Score
                          </span>
                        </div>

                        <div className="p-3.5 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15 text-xs font-mono space-y-1">
                          <span className="text-[#1E2748] font-sans text-[10px] block font-bold">TRANSACTION AUDIT VERDICT</span>
                          <span className="font-bold text-[#1E2748] text-sm block">{analysisResult.transactionId}</span>
                          <span className="text-red-600 block font-bold">Risk Tag: {analysisResult.riskTag}</span>
                        </div>

                        <div className="space-y-2 text-xs">
                          <span className="font-bold text-[#1E2748] block text-[11px] uppercase tracking-wider">Detected Anomaly Signals:</span>
                          {analysisResult.anomalyFactors?.map((f, i) => (
                            <div key={i} className="p-2 bg-[#FAF7E6] rounded-lg border border-red-500/30 text-red-700 flex items-center space-x-2 text-[11px]">
                              <AlertTriangle className="w-3.5 h-3.5 text-red-600 flex-shrink-0" />
                              <span>{f}</span>
                            </div>
                          ))}
                        </div>

                        <div className="p-3.5 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15 text-xs italic text-[#1E2748] space-y-1">
                          <span className="font-bold text-[#1E2748] not-italic block flex items-center space-x-1.5">
                            <Sparkles className="w-3.5 h-3.5 text-[#C59E5F]" />
                            <span>Gemini Fraud Summary:</span>
                          </span>
                          <p className="text-[#1E2748]">"{analysisResult.aiFraudSummary}"</p>
                        </div>

                        <button
                          onClick={() => handleGenerateFinCENSar(analysisResult)}
                          className="w-full py-2.5 bg-[#1E2748] hover:bg-[#141C33] text-[#FAF7E6] font-bold text-xs rounded-xl shadow transition flex items-center justify-center space-x-2"
                        >
                          <FileText className="w-4 h-4 text-[#C59E5F]" />
                          <span>Generate Regulatory FinCEN SAR Report</span>
                        </button>
                      </div>
                    ) : (
                      <div className="glass-panel p-8 rounded-2xl border border-[#1E2748]/15 text-center text-[#1E2748] text-xs space-y-2 bg-[#F3EEDC]">
                        <ShieldAlert className="w-8 h-8 text-[#1E2748] mx-auto" />
                        <p>Click "Run AI Audit" on any flagged transaction to generate deep Gemini anomaly diagnostic signals.</p>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: LIVE AML ANOMALY SIMULATOR */}
          {activeTab === 'simulator' && (
            <div className="glass-panel p-6 rounded-2xl border border-[#1E2748]/15 bg-[#F3EEDC] shadow-xl max-w-3xl space-y-5">
              <h3 className="text-sm font-bold text-[#1E2748] flex items-center space-x-2 pb-3 border-b border-[#1E2748]/15">
                <Zap className="w-4 h-4 text-[#C59E5F]" />
                <span>Simulate High-Risk Transaction Signal</span>
              </h3>

              <form onSubmit={handleRunSimulator} className="space-y-4 text-xs">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">ACCOUNT HOLDER</label>
                    <input
                      type="text"
                      value={simTx.accountHolder}
                      onChange={(e) => setSimTx({ ...simTx, accountHolder: e.target.value })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748] font-bold"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">ACCOUNT NUMBER</label>
                    <input
                      type="text"
                      value={simTx.accountNumber}
                      onChange={(e) => setSimTx({ ...simTx, accountNumber: e.target.value })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748] font-mono font-bold"
                      required
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">TRANSACTION AMOUNT ($)</label>
                    <input
                      type="number"
                      value={simTx.amount}
                      onChange={(e) => setSimTx({ ...simTx, amount: Number(e.target.value) })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748] font-mono font-bold"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">TRANSACTION TYPE</label>
                    <select
                      value={simTx.transactionType}
                      onChange={(e) => setSimTx({ ...simTx, transactionType: e.target.value })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748]"
                    >
                      <option value="International SWIFT Wire">International SWIFT Wire</option>
                      <option value="Crypto Vault Off-Ramp">Crypto Vault Off-Ramp</option>
                      <option value="Rapid ACH Structuring Outflow">Rapid ACH Structuring Outflow</option>
                      <option value="High-Volume Cash Deposit">High-Volume Cash Deposit</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">ORIGINATION LOCATION & IP</label>
                    <input
                      type="text"
                      value={simTx.location}
                      onChange={(e) => setSimTx({ ...simTx, location: e.target.value })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748]"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-[#1E2748] font-bold mb-1 uppercase text-[10px]">HISTORICAL AVG AMOUNT ($)</label>
                    <input
                      type="number"
                      value={simTx.averageTransactionAmount}
                      onChange={(e) => setSimTx({ ...simTx, averageTransactionAmount: Number(e.target.value) })}
                      className="w-full bg-[#FAF7E6] border border-[#1E2748]/20 rounded-xl p-2.5 text-[#1E2748] font-mono"
                      required
                    />
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={simulating}
                  className="w-full py-3 bg-[#1E2748] hover:bg-[#141C33] text-[#FAF7E6] font-bold text-xs rounded-xl shadow-lg transition flex items-center justify-center space-x-2 disabled:opacity-50"
                >
                  <Sparkles className="w-4 h-4 text-[#C59E5F]" />
                  <span>{simulating ? 'Simulating Anomaly Stream...' : 'Inject & Run Gemini AML Detection Engine'}</span>
                </button>
              </form>
            </div>
          )}

          {/* TAB 3: FINCEN SAR REPORT GENERATOR */}
          {activeTab === 'sar_generator' && (
            <div className="glass-panel p-6 rounded-2xl border border-[#1E2748]/15 bg-[#F3EEDC] shadow-2xl space-y-5 max-w-4xl">
              {generatingSar ? (
                <div className="p-8 text-center">
                  <LoadingSpinner text="Generating official FinCEN Suspicious Activity Report (SAR)..." />
                </div>
              ) : sarReport ? (
                <div className="space-y-4 text-xs font-mono">
                  <div className="flex justify-between items-center pb-3 border-b border-[#1E2748]/15">
                    <h3 className="text-sm font-bold text-[#1E2748] font-sans flex items-center space-x-2">
                      <FileText className="w-4 h-4 text-[#C59E5F]" />
                      <span>Official FinCEN Suspicious Activity Report (Form 111)</span>
                    </h3>
                    <span className="px-2.5 py-0.5 bg-[#1E2748] text-[#FAF7E6] rounded text-[10px] font-bold">{sarReport.sarId}</span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15">
                    <div>
                      <span className="text-[10px] text-[#1E2748] font-sans block font-bold uppercase">SUBJECT NAME</span>
                      <span className="font-extrabold text-[#1E2748]">{sarReport.subjectName}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-[#1E2748] font-sans block font-bold uppercase">SUBJECT ACCOUNT</span>
                      <span className="font-extrabold text-[#1E2748]">{sarReport.subjectAccount}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-[#1E2748] font-sans block font-bold uppercase">TOTAL SUSPICIOUS AMOUNT</span>
                      <span className="font-black text-red-600">${sarReport.totalSuspiciousAmount.toLocaleString()}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-[#1E2748] font-sans block font-bold uppercase">REGULATORY FILING DATE</span>
                      <span className="font-bold text-[#1E2748]">{sarReport.regulatoryFilingDate}</span>
                    </div>
                  </div>

                  <div className="p-4 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15 space-y-1.5 font-sans">
                    <span className="font-bold text-[#1E2748] block text-[11px] uppercase">FinCEN Regulatory Narrative Summary:</span>
                    <p className="text-[#1E2748] leading-relaxed italic">"{sarReport.narrativeSummary}"</p>
                  </div>

                  <div className="p-4 bg-[#FAF7E6] rounded-xl border border-[#1E2748]/15 flex justify-between items-center font-sans">
                    <span className="text-[#1E2748] font-bold text-xs">RECOMMENDED COMPLIANCE ACTION:</span>
                    <span className="font-black text-red-600 text-xs">{sarReport.recommendedAction}</span>
                  </div>
                </div>
              ) : (
                <div className="p-8 text-center text-[#1E2748] text-xs space-y-2">
                  <FileText className="w-8 h-8 text-[#1E2748] mx-auto" />
                  <p>Click "Generate SAR" on any suspicious transaction to construct a FinCEN regulatory report.</p>
                  <button
                    onClick={() => handleGenerateFinCENSar(fraudAlerts[0])}
                    className="px-4 py-2 bg-[#1E2748] text-[#FAF7E6] font-bold rounded-xl shadow transition"
                  >
                    Generate Sample FinCEN SAR Report
                  </button>
                </div>
              )}
            </div>
          )}
        </main>
      </div>
    </div>
  );
};
export default FraudDetectionPage;
